sitename: Marzhill Musings
host: jeremy.marzhillstudios.com
author: Jeremy Wall
dirs:
    static: _static
    content: _content
    output: generated
    template: _tmpl
tmpl:
    article: page.html
    collection: page.html
    tagcloud: page.html
